// This file is generated by npm run build:icons

export type IconName =
  | "brand/facebook"
  | "brand/instagram"
  | "brand/pinterest"
  | "phosphor/arrow-circle-right"
  | "radix/arrow-right"
  | "radix/calendar"
  | "radix/envelope-closed"
  | "radix/github-logo"
  | "radix/globe"
  | "radix/hamburger-menu"
  | "radix/linkedin-logo"
  | "radix/phone"
