/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    links: Link;
    cvs: Cv;
    letters: Letter;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    cvs: CvsSelect<false> | CvsSelect<true>;
    letters: LettersSelect<false> | LettersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    sideDrawer: SideDrawer;
    settings: Settings;
    sidebars: Sidebars;
    getInTouch: GetInTouch;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    sideDrawer: SideDrawerSelect<false> | SideDrawerSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    sidebars: SidebarsSelect<false> | SidebarsSelect<true>;
    getInTouch: GetInTouchSelect<false> | GetInTouchSelect<true>;
  };
  locale: 'fr' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  globalsToShow?: {
    rightSidebar?: boolean | null;
    footer?: boolean | null;
  };
  layout?:
    | (
        | {
            hasMultipleColumns?: boolean | null;
            columns?:
              | {
                  size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  enableLink?: boolean | null;
                  link?: {
                    type?: ('reference' | 'custom' | 'current') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: string | Page;
                    } | null;
                    url?: string | null;
                    label: string;
                    /**
                     * Dictates how the link should be rendered.
                     */
                    appearance?:
                      | (
                          | 'default'
                          | 'destructive'
                          | 'ghost'
                          | 'link'
                          | 'outline'
                          | 'text'
                          | 'secondary'
                          | 'underline'
                          | 'underlineSimple'
                          | 'iconOnly'
                          | 'menu'
                          | 'categoryLabel'
                          | 'richtextLink'
                          | 'sideDrawer'
                        )
                      | null;
                    /**
                     * Highlights the link based on the URL
                     */
                    isActive?: ('default' | 'exact' | 'never') | null;
                    isSheet?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            column?: {
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              enableLink?: boolean | null;
              link?: {
                type?: ('reference' | 'custom' | 'current') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                label: string;
                /**
                 * Dictates how the link should be rendered.
                 */
                appearance?:
                  | (
                      | 'default'
                      | 'destructive'
                      | 'ghost'
                      | 'link'
                      | 'outline'
                      | 'text'
                      | 'secondary'
                      | 'underline'
                      | 'underlineSimple'
                      | 'iconOnly'
                      | 'menu'
                      | 'categoryLabel'
                      | 'richtextLink'
                      | 'sideDrawer'
                    )
                  | null;
                /**
                 * Highlights the link based on the URL
                 */
                isActive?: ('default' | 'exact' | 'never') | null;
                isSheet?: boolean | null;
              };
            };
            gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            blockTitle: string;
            populateBy: 'collection';
            relationTo?: ('cvs' | 'letters') | null;
            cardVariant?: ('cv' | 'link' | 'letter') | null;
            layout?: ('grid' | 'carousel' | 'horizontalScroll' | 'verticalList' | 'horizontalWrap') | null;
            imageSelector?: ('images' | 'dots') | null;
            hasLimit?: boolean | null;
            limit?: number | null;
            hasPagination?: boolean | null;
            gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
            id?: string | null;
            blockName?: string | null;
            blockType: 'itemsList';
          }
        | {
            relationTo?: 'blogs' | null;
            layout?:
              | {
                  blockType?: ('content' | 'titleSection') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicContent';
          }
        | {
            type?: ('highImpact' | 'lowImpact' | 'mediumImpact') | null;
            /**
             * Only available for dynamic-content
             */
            useDocuementFields?: boolean | null;
            title?: string | null;
            subtitle?: string | null;
            showImage?: boolean | null;
            image?: (string | null) | Media;
            gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
            id?: string | null;
            blockName?: string | null;
            blockType: 'titleSection';
          }
        | {
            type?: ('cv' | 'letter') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documentViewer';
          }
      )[]
    | null;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('super' | 'admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: string;
  title: string;
  link: {
    type?: ('reference' | 'custom' | 'current') | null;
    newTab?: boolean | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
    label: string;
    /**
     * Dictates how the link should be rendered.
     */
    appearance?:
      | (
          | 'default'
          | 'destructive'
          | 'ghost'
          | 'link'
          | 'outline'
          | 'text'
          | 'secondary'
          | 'underline'
          | 'underlineSimple'
          | 'iconOnly'
          | 'menu'
          | 'categoryLabel'
          | 'richtextLink'
          | 'sideDrawer'
        )
      | null;
    /**
     * Highlights the link based on the URL
     */
    isActive?: ('default' | 'exact' | 'never') | null;
    isSheet?: boolean | null;
  };
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cvs".
 */
export interface Cv {
  id: string;
  publishedOn?: string | null;
  slug: string;
  infos?: {
    /**
     * Fill in your contact infos in the global Get In Touch section.
     */
    jobTitle?: string | null;
  };
  introduction: {
    tabName?: string | null;
    content: (
      | {
          hasMultipleColumns?: boolean | null;
          columns?:
            | {
                size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                richText?: {
                  root: {
                    type: string;
                    children: {
                      type: string;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                enableLink?: boolean | null;
                link?: {
                  type?: ('reference' | 'custom' | 'current') | null;
                  newTab?: boolean | null;
                  reference?: {
                    relationTo: 'pages';
                    value: string | Page;
                  } | null;
                  url?: string | null;
                  label: string;
                  /**
                   * Dictates how the link should be rendered.
                   */
                  appearance?:
                    | (
                        | 'default'
                        | 'destructive'
                        | 'ghost'
                        | 'link'
                        | 'outline'
                        | 'text'
                        | 'secondary'
                        | 'underline'
                        | 'underlineSimple'
                        | 'iconOnly'
                        | 'menu'
                        | 'categoryLabel'
                        | 'richtextLink'
                        | 'sideDrawer'
                      )
                    | null;
                  /**
                   * Highlights the link based on the URL
                   */
                  isActive?: ('default' | 'exact' | 'never') | null;
                  isSheet?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          column?: {
            richText?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            enableLink?: boolean | null;
            link?: {
              type?: ('reference' | 'custom' | 'current') | null;
              newTab?: boolean | null;
              reference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              url?: string | null;
              label: string;
              /**
               * Dictates how the link should be rendered.
               */
              appearance?:
                | (
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'text'
                    | 'secondary'
                    | 'underline'
                    | 'underlineSimple'
                    | 'iconOnly'
                    | 'menu'
                    | 'categoryLabel'
                    | 'richtextLink'
                    | 'sideDrawer'
                  )
                | null;
              /**
               * Highlights the link based on the URL
               */
              isActive?: ('default' | 'exact' | 'never') | null;
              isSheet?: boolean | null;
            };
          };
          gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
          id?: string | null;
          blockName?: string | null;
          blockType: 'content';
        }
      | {
          type?: ('highImpact' | 'lowImpact' | 'mediumImpact') | null;
          /**
           * Only available for dynamic-content
           */
          useDocuementFields?: boolean | null;
          title?: string | null;
          subtitle?: string | null;
          showImage?: boolean | null;
          image?: (string | null) | Media;
          gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
          id?: string | null;
          blockName?: string | null;
          blockType: 'titleSection';
        }
    )[];
  };
  skills?: {
    pages?:
      | {
          competences?: {
            tabName?: string | null;
            softSkills?:
              | {
                  title?: string | null;
                  id?: string | null;
                }[]
              | null;
            hardSkills?:
              | {
                  title?: string | null;
                  level?: ('beginner' | 'intermediate' | 'advanced') | null;
                  id?: string | null;
                }[]
              | null;
          };
          education?: {
            tabName?: string | null;
            education?:
              | {
                  program?: string | null;
                  school?: string | null;
                  startDate?: string | null;
                  endDate?: string | null;
                  content?:
                    | {
                        hasMultipleColumns?: boolean | null;
                        columns?:
                          | {
                              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                              richText?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: string;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom' | 'current') | null;
                                newTab?: boolean | null;
                                reference?: {
                                  relationTo: 'pages';
                                  value: string | Page;
                                } | null;
                                url?: string | null;
                                label: string;
                                /**
                                 * Dictates how the link should be rendered.
                                 */
                                appearance?:
                                  | (
                                      | 'default'
                                      | 'destructive'
                                      | 'ghost'
                                      | 'link'
                                      | 'outline'
                                      | 'text'
                                      | 'secondary'
                                      | 'underline'
                                      | 'underlineSimple'
                                      | 'iconOnly'
                                      | 'menu'
                                      | 'categoryLabel'
                                      | 'richtextLink'
                                      | 'sideDrawer'
                                    )
                                  | null;
                                /**
                                 * Highlights the link based on the URL
                                 */
                                isActive?: ('default' | 'exact' | 'never') | null;
                                isSheet?: boolean | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        column?: {
                          richText?: {
                            root: {
                              type: string;
                              children: {
                                type: string;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          } | null;
                          enableLink?: boolean | null;
                          link?: {
                            type?: ('reference' | 'custom' | 'current') | null;
                            newTab?: boolean | null;
                            reference?: {
                              relationTo: 'pages';
                              value: string | Page;
                            } | null;
                            url?: string | null;
                            label: string;
                            /**
                             * Dictates how the link should be rendered.
                             */
                            appearance?:
                              | (
                                  | 'default'
                                  | 'destructive'
                                  | 'ghost'
                                  | 'link'
                                  | 'outline'
                                  | 'text'
                                  | 'secondary'
                                  | 'underline'
                                  | 'underlineSimple'
                                  | 'iconOnly'
                                  | 'menu'
                                  | 'categoryLabel'
                                  | 'richtextLink'
                                  | 'sideDrawer'
                                )
                              | null;
                            /**
                             * Highlights the link based on the URL
                             */
                            isActive?: ('default' | 'exact' | 'never') | null;
                            isSheet?: boolean | null;
                          };
                        };
                        gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'content';
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
          };
          experiences?: {
            tabName?: string | null;
            experience?:
              | {
                  title?: string | null;
                  hasLink?: boolean | null;
                  link?: {
                    type?: ('reference' | 'custom' | 'current') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: string | Page;
                    } | null;
                    url?: string | null;
                    label: string;
                    /**
                     * Dictates how the link should be rendered.
                     */
                    appearance?:
                      | (
                          | 'default'
                          | 'destructive'
                          | 'ghost'
                          | 'link'
                          | 'outline'
                          | 'text'
                          | 'secondary'
                          | 'underline'
                          | 'underlineSimple'
                          | 'iconOnly'
                          | 'menu'
                          | 'categoryLabel'
                          | 'richtextLink'
                          | 'sideDrawer'
                        )
                      | null;
                    /**
                     * Highlights the link based on the URL
                     */
                    isActive?: ('default' | 'exact' | 'never') | null;
                    isSheet?: boolean | null;
                  };
                  company?: string | null;
                  description?: string | null;
                  startDate?: string | null;
                  toPresent?: boolean | null;
                  endDate?: string | null;
                  content?:
                    | {
                        hasMultipleColumns?: boolean | null;
                        columns?:
                          | {
                              size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                              richText?: {
                                root: {
                                  type: string;
                                  children: {
                                    type: string;
                                    version: number;
                                    [k: string]: unknown;
                                  }[];
                                  direction: ('ltr' | 'rtl') | null;
                                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                  indent: number;
                                  version: number;
                                };
                                [k: string]: unknown;
                              } | null;
                              enableLink?: boolean | null;
                              link?: {
                                type?: ('reference' | 'custom' | 'current') | null;
                                newTab?: boolean | null;
                                reference?: {
                                  relationTo: 'pages';
                                  value: string | Page;
                                } | null;
                                url?: string | null;
                                label: string;
                                /**
                                 * Dictates how the link should be rendered.
                                 */
                                appearance?:
                                  | (
                                      | 'default'
                                      | 'destructive'
                                      | 'ghost'
                                      | 'link'
                                      | 'outline'
                                      | 'text'
                                      | 'secondary'
                                      | 'underline'
                                      | 'underlineSimple'
                                      | 'iconOnly'
                                      | 'menu'
                                      | 'categoryLabel'
                                      | 'richtextLink'
                                      | 'sideDrawer'
                                    )
                                  | null;
                                /**
                                 * Highlights the link based on the URL
                                 */
                                isActive?: ('default' | 'exact' | 'never') | null;
                                isSheet?: boolean | null;
                              };
                              id?: string | null;
                            }[]
                          | null;
                        column?: {
                          richText?: {
                            root: {
                              type: string;
                              children: {
                                type: string;
                                version: number;
                                [k: string]: unknown;
                              }[];
                              direction: ('ltr' | 'rtl') | null;
                              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                              indent: number;
                              version: number;
                            };
                            [k: string]: unknown;
                          } | null;
                          enableLink?: boolean | null;
                          link?: {
                            type?: ('reference' | 'custom' | 'current') | null;
                            newTab?: boolean | null;
                            reference?: {
                              relationTo: 'pages';
                              value: string | Page;
                            } | null;
                            url?: string | null;
                            label: string;
                            /**
                             * Dictates how the link should be rendered.
                             */
                            appearance?:
                              | (
                                  | 'default'
                                  | 'destructive'
                                  | 'ghost'
                                  | 'link'
                                  | 'outline'
                                  | 'text'
                                  | 'secondary'
                                  | 'underline'
                                  | 'underlineSimple'
                                  | 'iconOnly'
                                  | 'menu'
                                  | 'categoryLabel'
                                  | 'richtextLink'
                                  | 'sideDrawer'
                                )
                              | null;
                            /**
                             * Highlights the link based on the URL
                             */
                            isActive?: ('default' | 'exact' | 'never') | null;
                            isSheet?: boolean | null;
                          };
                        };
                        gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
                        id?: string | null;
                        blockName?: string | null;
                        blockType: 'content';
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  parent?: (string | null) | Cv;
  breadcrumbs?:
    | {
        doc?: (string | null) | Cv;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters".
 */
export interface Letter {
  id: string;
  publishedOn?: string | null;
  slug: string;
  company?: {
    name?: string | null;
    address?: string | null;
    city?: string | null;
    country?: string | null;
    zip?: string | null;
    phone?: string | null;
  };
  letter: {
    subject: string;
    content: {
      hasMultipleColumns?: boolean | null;
      columns?:
        | {
            size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
            richText?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            enableLink?: boolean | null;
            link?: {
              type?: ('reference' | 'custom' | 'current') | null;
              newTab?: boolean | null;
              reference?: {
                relationTo: 'pages';
                value: string | Page;
              } | null;
              url?: string | null;
              label: string;
              /**
               * Dictates how the link should be rendered.
               */
              appearance?:
                | (
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'text'
                    | 'secondary'
                    | 'underline'
                    | 'underlineSimple'
                    | 'iconOnly'
                    | 'menu'
                    | 'categoryLabel'
                    | 'richtextLink'
                    | 'sideDrawer'
                  )
                | null;
              /**
               * Highlights the link based on the URL
               */
              isActive?: ('default' | 'exact' | 'never') | null;
              isSheet?: boolean | null;
            };
            id?: string | null;
          }[]
        | null;
      column?: {
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom' | 'current') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Dictates how the link should be rendered.
           */
          appearance?:
            | (
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'text'
                | 'secondary'
                | 'underline'
                | 'underlineSimple'
                | 'iconOnly'
                | 'menu'
                | 'categoryLabel'
                | 'richtextLink'
                | 'sideDrawer'
              )
            | null;
          /**
           * Highlights the link based on the URL
           */
          isActive?: ('default' | 'exact' | 'never') | null;
          isSheet?: boolean | null;
        };
      };
      gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
      id?: string | null;
      blockName?: string | null;
      blockType: 'content';
    }[];
  };
  parent?: (string | null) | Letter;
  breadcrumbs?:
    | {
        doc?: (string | null) | Letter;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'links';
        value: string | Link;
      } | null)
    | ({
        relationTo: 'cvs';
        value: string | Cv;
      } | null)
    | ({
        relationTo: 'letters';
        value: string | Letter;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  globalsToShow?:
    | T
    | {
        rightSidebar?: T;
        footer?: T;
      };
  layout?:
    | T
    | {
        content?:
          | T
          | {
              hasMultipleColumns?: T;
              columns?:
                | T
                | {
                    size?: T;
                    richText?: T;
                    enableLink?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                          isActive?: T;
                          isSheet?: T;
                        };
                    id?: T;
                  };
              column?:
                | T
                | {
                    richText?: T;
                    enableLink?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                          isActive?: T;
                          isSheet?: T;
                        };
                  };
              gutter?: T;
              id?: T;
              blockName?: T;
            };
        itemsList?:
          | T
          | {
              blockTitle?: T;
              populateBy?: T;
              relationTo?: T;
              cardVariant?: T;
              layout?: T;
              imageSelector?: T;
              hasLimit?: T;
              limit?: T;
              hasPagination?: T;
              gutter?: T;
              id?: T;
              blockName?: T;
            };
        dynamicContent?:
          | T
          | {
              relationTo?: T;
              layout?:
                | T
                | {
                    blockType?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        titleSection?:
          | T
          | {
              type?: T;
              useDocuementFields?: T;
              title?: T;
              subtitle?: T;
              showImage?: T;
              image?: T;
              gutter?: T;
              id?: T;
              blockName?: T;
            };
        documentViewer?:
          | T
          | {
              type?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  title?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
        isActive?: T;
        isSheet?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cvs_select".
 */
export interface CvsSelect<T extends boolean = true> {
  publishedOn?: T;
  slug?: T;
  infos?:
    | T
    | {
        jobTitle?: T;
      };
  introduction?:
    | T
    | {
        tabName?: T;
        content?:
          | T
          | {
              content?:
                | T
                | {
                    hasMultipleColumns?: T;
                    columns?:
                      | T
                      | {
                          size?: T;
                          richText?: T;
                          enableLink?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                                isActive?: T;
                                isSheet?: T;
                              };
                          id?: T;
                        };
                    column?:
                      | T
                      | {
                          richText?: T;
                          enableLink?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                                isActive?: T;
                                isSheet?: T;
                              };
                        };
                    gutter?: T;
                    id?: T;
                    blockName?: T;
                  };
              titleSection?:
                | T
                | {
                    type?: T;
                    useDocuementFields?: T;
                    title?: T;
                    subtitle?: T;
                    showImage?: T;
                    image?: T;
                    gutter?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  skills?:
    | T
    | {
        pages?:
          | T
          | {
              competences?:
                | T
                | {
                    tabName?: T;
                    softSkills?:
                      | T
                      | {
                          title?: T;
                          id?: T;
                        };
                    hardSkills?:
                      | T
                      | {
                          title?: T;
                          level?: T;
                          id?: T;
                        };
                  };
              education?:
                | T
                | {
                    tabName?: T;
                    education?:
                      | T
                      | {
                          program?: T;
                          school?: T;
                          startDate?: T;
                          endDate?: T;
                          content?:
                            | T
                            | {
                                content?:
                                  | T
                                  | {
                                      hasMultipleColumns?: T;
                                      columns?:
                                        | T
                                        | {
                                            size?: T;
                                            richText?: T;
                                            enableLink?: T;
                                            link?:
                                              | T
                                              | {
                                                  type?: T;
                                                  newTab?: T;
                                                  reference?: T;
                                                  url?: T;
                                                  label?: T;
                                                  appearance?: T;
                                                  isActive?: T;
                                                  isSheet?: T;
                                                };
                                            id?: T;
                                          };
                                      column?:
                                        | T
                                        | {
                                            richText?: T;
                                            enableLink?: T;
                                            link?:
                                              | T
                                              | {
                                                  type?: T;
                                                  newTab?: T;
                                                  reference?: T;
                                                  url?: T;
                                                  label?: T;
                                                  appearance?: T;
                                                  isActive?: T;
                                                  isSheet?: T;
                                                };
                                          };
                                      gutter?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                        };
                  };
              experiences?:
                | T
                | {
                    tabName?: T;
                    experience?:
                      | T
                      | {
                          title?: T;
                          hasLink?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                                isActive?: T;
                                isSheet?: T;
                              };
                          company?: T;
                          description?: T;
                          startDate?: T;
                          toPresent?: T;
                          endDate?: T;
                          content?:
                            | T
                            | {
                                content?:
                                  | T
                                  | {
                                      hasMultipleColumns?: T;
                                      columns?:
                                        | T
                                        | {
                                            size?: T;
                                            richText?: T;
                                            enableLink?: T;
                                            link?:
                                              | T
                                              | {
                                                  type?: T;
                                                  newTab?: T;
                                                  reference?: T;
                                                  url?: T;
                                                  label?: T;
                                                  appearance?: T;
                                                  isActive?: T;
                                                  isSheet?: T;
                                                };
                                            id?: T;
                                          };
                                      column?:
                                        | T
                                        | {
                                            richText?: T;
                                            enableLink?: T;
                                            link?:
                                              | T
                                              | {
                                                  type?: T;
                                                  newTab?: T;
                                                  reference?: T;
                                                  url?: T;
                                                  label?: T;
                                                  appearance?: T;
                                                  isActive?: T;
                                                  isSheet?: T;
                                                };
                                          };
                                      gutter?: T;
                                      id?: T;
                                      blockName?: T;
                                    };
                              };
                          id?: T;
                        };
                  };
              id?: T;
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "letters_select".
 */
export interface LettersSelect<T extends boolean = true> {
  publishedOn?: T;
  slug?: T;
  company?:
    | T
    | {
        name?: T;
        address?: T;
        city?: T;
        country?: T;
        zip?: T;
        phone?: T;
      };
  letter?:
    | T
    | {
        subject?: T;
        content?:
          | T
          | {
              content?:
                | T
                | {
                    hasMultipleColumns?: T;
                    columns?:
                      | T
                      | {
                          size?: T;
                          richText?: T;
                          enableLink?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                                isActive?: T;
                                isSheet?: T;
                              };
                          id?: T;
                        };
                    column?:
                      | T
                      | {
                          richText?: T;
                          enableLink?: T;
                          link?:
                            | T
                            | {
                                type?: T;
                                newTab?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                                appearance?: T;
                                isActive?: T;
                                isSheet?: T;
                              };
                        };
                    gutter?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  links?: (string | Link)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sideDrawer".
 */
export interface SideDrawer {
  id: string;
  header?: {};
  body?: {
    content?: {
      layout?:
        | (
            | {
                hasMultipleColumns?: boolean | null;
                columns?:
                  | {
                      size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
                      richText?: {
                        root: {
                          type: string;
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      enableLink?: boolean | null;
                      link?: {
                        type?: ('reference' | 'custom' | 'current') | null;
                        newTab?: boolean | null;
                        reference?: {
                          relationTo: 'pages';
                          value: string | Page;
                        } | null;
                        url?: string | null;
                        label: string;
                        /**
                         * Dictates how the link should be rendered.
                         */
                        appearance?:
                          | (
                              | 'default'
                              | 'destructive'
                              | 'ghost'
                              | 'link'
                              | 'outline'
                              | 'text'
                              | 'secondary'
                              | 'underline'
                              | 'underlineSimple'
                              | 'iconOnly'
                              | 'menu'
                              | 'categoryLabel'
                              | 'richtextLink'
                              | 'sideDrawer'
                            )
                          | null;
                        /**
                         * Highlights the link based on the URL
                         */
                        isActive?: ('default' | 'exact' | 'never') | null;
                        isSheet?: boolean | null;
                      };
                      id?: string | null;
                    }[]
                  | null;
                column?: {
                  richText?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  enableLink?: boolean | null;
                  link?: {
                    type?: ('reference' | 'custom' | 'current') | null;
                    newTab?: boolean | null;
                    reference?: {
                      relationTo: 'pages';
                      value: string | Page;
                    } | null;
                    url?: string | null;
                    label: string;
                    /**
                     * Dictates how the link should be rendered.
                     */
                    appearance?:
                      | (
                          | 'default'
                          | 'destructive'
                          | 'ghost'
                          | 'link'
                          | 'outline'
                          | 'text'
                          | 'secondary'
                          | 'underline'
                          | 'underlineSimple'
                          | 'iconOnly'
                          | 'menu'
                          | 'categoryLabel'
                          | 'richtextLink'
                          | 'sideDrawer'
                        )
                      | null;
                    /**
                     * Highlights the link based on the URL
                     */
                    isActive?: ('default' | 'exact' | 'never') | null;
                    isSheet?: boolean | null;
                  };
                };
                gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
                id?: string | null;
                blockName?: string | null;
                blockType: 'content';
              }
            | {
                blockTitle: string;
                populateBy: 'collection';
                relationTo?: ('cvs' | 'letters') | null;
                cardVariant?: ('cv' | 'link' | 'letter') | null;
                layout?: ('grid' | 'carousel' | 'horizontalScroll' | 'verticalList' | 'horizontalWrap') | null;
                imageSelector?: ('images' | 'dots') | null;
                hasLimit?: boolean | null;
                limit?: number | null;
                hasPagination?: boolean | null;
                gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
                id?: string | null;
                blockName?: string | null;
                blockType: 'itemsList';
              }
            | {
                type?: ('highImpact' | 'lowImpact' | 'mediumImpact') | null;
                /**
                 * Only available for dynamic-content
                 */
                useDocuementFields?: boolean | null;
                title?: string | null;
                subtitle?: string | null;
                showImage?: boolean | null;
                image?: (string | null) | Media;
                gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
                id?: string | null;
                blockName?: string | null;
                blockType: 'titleSection';
              }
          )[]
        | null;
    };
  };
  footer?: {};
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: string;
  underConstruction?: boolean | null;
  disableAnalytics?: boolean | null;
  showLocaleSwitcher?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebars".
 */
export interface Sidebars {
  id: string;
  right?: {
    sections?:
      | (
          | {
              blockTitle: string;
              populateBy: 'collection';
              relationTo?: ('cvs' | 'letters') | null;
              cardVariant?: ('cv' | 'link' | 'letter') | null;
              layout?: ('grid' | 'carousel' | 'horizontalScroll' | 'verticalList' | 'horizontalWrap') | null;
              imageSelector?: ('images' | 'dots') | null;
              hasLimit?: boolean | null;
              limit?: number | null;
              hasPagination?: boolean | null;
              gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
              id?: string | null;
              blockName?: string | null;
              blockType: 'itemsList';
            }
          | {
              type?: ('highImpact' | 'lowImpact' | 'mediumImpact') | null;
              /**
               * Only available for dynamic-content
               */
              useDocuementFields?: boolean | null;
              title?: string | null;
              subtitle?: string | null;
              showImage?: boolean | null;
              image?: (string | null) | Media;
              gutter: 'small' | 'medium' | 'large' | 'container' | 'none';
              id?: string | null;
              blockName?: string | null;
              blockType: 'titleSection';
            }
        )[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "getInTouch".
 */
export interface GetInTouch {
  id: string;
  candidateName?: string | null;
  contactInfos?:
    | {
        isLink?: boolean | null;
        type?:
          | ('radix/envelope-closed' | 'radix/phone' | 'radix/globe' | 'radix/github-logo' | 'radix/linkedin-logo')
          | null;
        value?: string | null;
        link?: {
          type?: ('reference' | 'custom' | 'current') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Dictates how the link should be rendered.
           */
          appearance?:
            | (
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'text'
                | 'secondary'
                | 'underline'
                | 'underlineSimple'
                | 'iconOnly'
                | 'menu'
                | 'categoryLabel'
                | 'richtextLink'
                | 'sideDrawer'
              )
            | null;
          /**
           * Highlights the link based on the URL
           */
          isActive?: ('default' | 'exact' | 'never') | null;
          isSheet?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sideDrawer_select".
 */
export interface SideDrawerSelect<T extends boolean = true> {
  header?: T | {};
  body?:
    | T
    | {
        content?:
          | T
          | {
              layout?:
                | T
                | {
                    content?:
                      | T
                      | {
                          hasMultipleColumns?: T;
                          columns?:
                            | T
                            | {
                                size?: T;
                                richText?: T;
                                enableLink?: T;
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                      appearance?: T;
                                      isActive?: T;
                                      isSheet?: T;
                                    };
                                id?: T;
                              };
                          column?:
                            | T
                            | {
                                richText?: T;
                                enableLink?: T;
                                link?:
                                  | T
                                  | {
                                      type?: T;
                                      newTab?: T;
                                      reference?: T;
                                      url?: T;
                                      label?: T;
                                      appearance?: T;
                                      isActive?: T;
                                      isSheet?: T;
                                    };
                              };
                          gutter?: T;
                          id?: T;
                          blockName?: T;
                        };
                    itemsList?:
                      | T
                      | {
                          blockTitle?: T;
                          populateBy?: T;
                          relationTo?: T;
                          cardVariant?: T;
                          layout?: T;
                          imageSelector?: T;
                          hasLimit?: T;
                          limit?: T;
                          hasPagination?: T;
                          gutter?: T;
                          id?: T;
                          blockName?: T;
                        };
                    titleSection?:
                      | T
                      | {
                          type?: T;
                          useDocuementFields?: T;
                          title?: T;
                          subtitle?: T;
                          showImage?: T;
                          image?: T;
                          gutter?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
            };
      };
  footer?: T | {};
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  underConstruction?: T;
  disableAnalytics?: T;
  showLocaleSwitcher?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebars_select".
 */
export interface SidebarsSelect<T extends boolean = true> {
  right?:
    | T
    | {
        sections?:
          | T
          | {
              itemsList?:
                | T
                | {
                    blockTitle?: T;
                    populateBy?: T;
                    relationTo?: T;
                    cardVariant?: T;
                    layout?: T;
                    imageSelector?: T;
                    hasLimit?: T;
                    limit?: T;
                    hasPagination?: T;
                    gutter?: T;
                    id?: T;
                    blockName?: T;
                  };
              titleSection?:
                | T
                | {
                    type?: T;
                    useDocuementFields?: T;
                    title?: T;
                    subtitle?: T;
                    showImage?: T;
                    image?: T;
                    gutter?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "getInTouch_select".
 */
export interface GetInTouchSelect<T extends boolean = true> {
  candidateName?: T;
  contactInfos?:
    | T
    | {
        isLink?: T;
        type?: T;
        value?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
              isActive?: T;
              isSheet?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}